services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html:z
    working_dir: /var/www/html
    container_name: helloCSE_app
    command: sh -c "chown -R www-data:www-data /var/www/html && php-fpm"
    depends_on:
      - db
    networks:
      - helloCSE

  web:
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z
    ports:
      - 8000:80
    depends_on:
      - app
    container_name: helloCSE_web
    networks:
      - helloCSE

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    container_name: helloCSE_db
    networks:
      - helloCSE

networks:
  helloCSE:
    driver: bridge

volumes:
  helloCSE_db:
